server {
    listen 80;
    server_name intranet.andina.test web.andina.test;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name intranet.andina.test web.andina.test localhost;

    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://10.10.30.21:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
