FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04
# Instalación mínima en imagen: nada que falle en build sin systemd.
# Todo lo pesado (OVS, gns3, ryu) se instala en setup.sh/postCreateCommand.
