[Server]
host = 0.0.0.0
port = 3080
images_path = /home/vscode/GNS3/images
projects_path = /home/vscode/GNS3/projects
appliances_path = /home/vscode/GNS3/appliances
report_errors = False
auto_start = True
daemon = True
pid = /tmp/gns3server.pid
log = /tmp/gns3server.log

[Dynamips]
allocate_aux_console_ports = False
mmap_support = True
nodiskfilter = False
ghost_ios_support = True
sparse_memory_support = True
dynamips_path = /usr/bin/dynamips

[Qemu]
enable_kvm = False
require_kvm = False
qemu_path = /usr/bin/qemu-system-x86_64

[VPCS]
vpcs_path = /usr/bin/vpcs

[Ubridge]
ubridge_path = /usr/bin/ubridge
