[global]
   workgroup = LAB
   server string = lab-archivos
   security = user
   map to guest = never
   server min protocol = SMB2
   server max protocol = SMB3
   # SMB1 deshabilitado explícitamente (SMB01)

[administracion]
   path = /srv/shares/administracion
   valid users = @adm
   read only = no

[ventas]
   path = /srv/shares/ventas
   valid users = @ventas
   read only = no

[comun]
   path = /srv/shares/comun
   valid users = @adm, @ventas
   read only = yes
